config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/user", to: "users#homepage", as: :user
  get "/user/pedalos", to: "users#homepage_pedalo", as: :user_pedalos
  resources :pedalos, only: [:index, :show, :new, :create] do
    resources :reservations, only: :create
  end

  # get "/pedalos/:pedalo_id/reservations", to: "reservations#index_res_pedalos", as: :pedalo_reservations
  get "/user/reservations", to: "reservations#index_res_users", as: :user_reservations
  get "/reservations/:id", to: "reservations#show", as: :reservation
  get "/pedalos/:pedalo_id/reservations/new", to: "reservations#new", as: :new_reservation
  post "/reservations/:id", to: "reservations#create"
  patch "/reservations/:id", to: "reservations#update"

  #   member do
  #     get 'reservations', to: 'reservations#index_res_pedalos'
  #   end
  #   resources :reservations, only: [:show, :new, :create, :update]
  # end
  # get 'reservations', to: 'reservations#index_res_users'

  get "/reservations/:reservation_id/reviews/new", to: "reviews#new", as: :new_review
  post "/pedalos/:pedalo_id", to: "reviews#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pedalo.rb
class Pedalo < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :reservations
  has_many :reviews, through: :reservations

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, :description, :price_per_hour, :address, presence: true
  validates :price_per_hour, numericality: { greater_than_or_equal_to: 15 }
  validates :name, length: { minimum: 3, maximum: 500 }
  has_one_attached :photo
end

app/models/reservation.rb
class TimeSlotValidator < ActiveModel::Validator
  def validate(record)
    record.errors.add(:start_time, "start time must be before end time") if record.start_time >= record.end_time
    state = false
    Reservation.where(pedalo: record.pedalo).each do |record2|
      state = true if in_common?(record, record2)
    end
    record.errors.add(:start_time, "time slot already used") if state
  end

  private

  def in_common?(record1, record2)
    return false if record1.id == record2.id

    !((record2.end_time < record1.start_time) || (record2.start_time > record1.end_time))
  end
end

class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :pedalo
  has_one :review, dependent: :destroy

  validates :start_time, :end_time, :accepted, :transaction_price, presence: true
  validates :accepted, acceptance: { accept: ['accepted', 'pending', 'declined'] }
  validates_with TimeSlotValidator
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation
  delegate :pedalo, to: :reservation

  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5
  }

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :pedalos, dependent: :destroy, :foreign_key => "owner_id"
  has_many :reservations
  validates :first_name, :last_name, :role, :email, :encrypted_password, presence: true
  validates :role, acceptance: { accept: ['admin', 'client', 'owner'] }
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pedalos_controller.rb
class PedalosController < ApplicationController
  def index
    @pedalos = Pedalo.all
    @markers = @pedalos.geocoded.map do |pedalo|
      {
        lat: pedalo.latitude,
        lng: pedalo.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pedalo: pedalo })
      }
    end
  end

  def show
    @pedalo = Pedalo.find(params[:id])
    @markers = [
      {
        lat: @pedalo.latitude,
        lng: @pedalo.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pedalo: @pedalo })
      }
    ]
    # @marker = @pedalo.geocoded.map do |pedalo|
    #   {
    #     lat: pedalo.latitude,
    #     lng: pedalo.longitude
    #   }
    # end
  end

  def new
    @pedalo = Pedalo.new
  end

  def create
    @pedalo = Pedalo.new(pedalo_params)
    @pedalo.price_per_hour = @pedalo.price_per_hour * 100
    @pedalo.owner = current_user
    if @pedalo.save!
      redirect_to pedalos_path
    else
      render :new
    end
  end

  private

  def pedalo_params
    params.require(:pedalo).permit(:name, :description, :price_per_hour, :address, :photo)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # before_action :find_pedalo

  def index_res_pedalos
    @sorted_reservations = []
    Reservation.where(pedalo: @pedalo).each { |res| @sorted_reservations << res }
    @sorted_reservations = @sorted_reservations.sort { |res1, res2| sort_reservation(res1, res2) }
  end

  def index_res_users
  end

  def show
    @reservation = Reservation.find(params[:id])
    @pedalo = @reservation.pedalo
  end

  def new
    find_pedalo
    @date = Time.now.strftime("%B %d, %Y")
    @reservation = Reservation.new
  end

  def create
    find_pedalo
    @reservation = Reservation.new(reservation_params)
    @reservation.pedalo = @pedalo
    @reservation.user = current_user
    @reservation.transaction_price = @pedalo.price_per_hour * (@reservation.end_time - @reservation.start_time).fdiv(3600).to_i
    if @reservation.save
      redirect_to reservation_path(@reservation.id)
    else
      render :new
    end
  end

  def update
    # find_pedalo
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_owner_param)
      redirect_to user_path # check link when route change
    else
      redirect_to reservation_path(@reservation)
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_time, :end_time)
  end

  def reservation_owner_param
    params.require(:reservation).permit(:accepted)
  end

  def find_pedalo
    @pedalo = Pedalo.find(params[:pedalo_id])
  end

  def sort_reservation(res1, res2)
    # res1 > res2 -> 1
    # res1 = res2 -> 0
    # res1 < res2 -> -1
    # pending avant autre, suivit de chronologique (start_time)

    return -1 if res1.accepted == "pending" && res2.accepted != "pending"

    return 1 if res1.accepted != "pending" && res2.accepted == "pending"

    return res1.start_time <=> res2.start_time
  end

  def after_date?(reservation, date)
    reservation.start_time >= date
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @new_review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.reservation_id = params[:reservation_id]
    if @review.save
      redirect_to pedalo_path(Reservation.find(params[:reservation_id]).pedalo)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def homepage
    @pedalos = Pedalo.where(owner: current_user).to_a
    @reservations_owner = []
    @pedalos.each { |pedalo| Reservation.where(pedalo: pedalo).each { |res| @reservations_owner << res } }
    @reservations_owner_pending = []
    @pedalos.each do |pedalo|
      Reservation.where(pedalo: pedalo, accepted: "pending").each do |res|
        @reservations_owner_pending << res
      end
    end
    @reservations = Reservation.where(user: current_user)
  end

  def homepage_pedalo
    redirect_to user_path if current_user.role == "client"
    @pedalos = Pedalo.where(owner: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waterbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "", class: "navbar-brand" do %>
    <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8V2dlin82r2-DzYYTOLgTh6b6bTKRswd6wA&usqp=CAU", id:'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "See all pedalos", pedalos_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My profile", user_path, class: "nav-link" %>
      </li>
      <% if signed_in? %>
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item dropdown">
        <%= link_to '', class: "navbar-brand" do %>
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/JenniferAnistonFeb09.jpg/220px-JenniferAnistonFeb09.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>


    <% unless notice.nil? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
    <p class="alert alert-info"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://cdn.shopify.com/s/files/1/0020/6487/5578/files/SunPleasure.Unicorn_1600x.jpg);">
  <div class="container-home">
    <h1><strong>Keep Calm and Pedalo!</strong></h1>
    <p>Waterbnb allows you to rent pedalos to have fun with you friends on Switzerland's beautiful lakes</p>
    <div id="button-login"><a class="btn btn-flat" href="<%= pedalos_path%>">LOGIN</a></div>
  </div>
</div>

app/views/pedalos/_card_pedalo.html.erb
<div class="d-flex m-3 flex-row justify-content-start align-items-center card-pedalo">
  <% if pedalo.photo.attached? %>
    <%= cl_image_tag pedalo.photo.key, height: 400, width: 400, crop: :fill %>
  <% end %>
  
  <div class="ml-3 p-1">
    <h3 class="text-nowrap"><%= pedalo.name %></h3>
    <h4 class="text-nowrap"><%= pedalo.location %></h4>
    <p class="text-nowrap"><%= "#{pedalo.price_per_hour/100}.#{pedalo.price_per_hour%100}" %> CHF per hour</p>
    <% reviews = pedalo.reviews %>
    <% if reviews.count.zero? %>
      <% rating = 4 %>
    <% else %>
      <% rating = 0 %>
      <% reviews.each { |review| rating += review.rating } %>
      <%= rating %>
      <% rating = rating.fdiv(reviews.count).round(0).to_i %>
    <% end %>
    <div class="rating-width">
      <%= render  'reviews/rating', rating: rating %>
    </div>
  </div>
</div>

app/views/pedalos/_info_window.html.erb
<!-- <div class="d-flex p-3 m-3 flex-row border align-items-center card-pedalo">
  <%= image_tag(pedalo.image_link) %>
  <div class="ml-3 p-1">
    <h3 class="text-nowrap"><%= pedalo.name %></h3>
    <h4 class="text-nowrap"><%= pedalo.location %></h4>
    <p class="text-nowrap"><%= "#{pedalo.price_per_hour/100}.#{pedalo.price_per_hour%100}" %> CHF/h</p>
  </div>
</div> -->

<div class="d-flex flex-row justify-content-start align-items-center card-info-reservation">
  <% if pedalo.photo.attached? %>
    <%= cl_image_tag pedalo.photo.key, height: 400, width: 400, crop: :fill %>
  <% end %>
  <div class="ml-3 p-1">
    <h3 class="text-nowrap"><%= pedalo.name %></h3>
    <h4 class="text-nowrap"><%= pedalo.location %></h4>
    <h4 class="text-nowrap"><%= pedalo.price_per_hour.fdiv(100).round(2) %> CHF per hour</h4>
  </div>
  <!--<div></div>-->
</div>

app/views/pedalos/index.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h1>Welcome to Waterbnb, <%= current_user.first_name %> !</h1>
<!--     <ul>
      <li>1 - Click on the pedalo of your choice</li>
      <li>2 - Proceed with the booking</li>
      <li>3 - Have fun and don't forget your life jacket!</li>
    </ul> -->

  </div>
</div>
<div class="main-container">
  <div class="container-index">
    <div class="d-flex flex-wrap justify-content-center">
      <% @pedalos.each do |pedalo| %>
      <a href="<%= pedalo_path(pedalo) %>" class="text-reset text-decoration-none">
        <%= render 'pedalos/card_pedalo', pedalo: pedalo %>
      </a>
      <% end %>
    </div>
  </div>

  <div id="map"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

  </div>
</div>

app/views/pedalos/new.html.erb
<h1 class="header-form">Fill out this form to add your pedalo!</h1>

<div class='form-addpedalo'>
  <%= simple_form_for @pedalo do |f| %>
    <%= f.input :name, placeholder: "What is your pedalo's nickname?"%>
    <%= f.input :description, placeholder: 'Tell us everything about your pedalo' %>
    <%= f.input :address, placeholder: 'Where is your pedalo located?' %>
    <%= f.input :price_per_hour, placeholder: 'Minimum amount of 15 CHF' %>
    <%=f.input :photo, as: :file %>
    <%= f.submit "Submit!", class: 'btn-submit' %>
  <% end %>
</div>

app/views/pedalos/show.html.erb
<div class='container-show-pedalo'>

  <div class='content-show'>
    <h2 id="title_show"><strong><%= @pedalo.name %></strong> (<%= @pedalo.price_per_hour.fdiv(100).round(2) %> CHF per hour)</h2>
    <% if @pedalo.photo.attached? %>
      <%= cl_image_tag @pedalo.photo.key %>
    <% end %>
    <h5 id="title_show" class="mb-3"><strong>Description</strong></h5>
    <p><%= @pedalo.description %></p>

    <hr class="mt-5 mb-4">

    <h5 id="title_show mt-5" class="mb-3"><strong>Location</strong></h5>

      <div id="map" class="map-show"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

      </div>

    <hr class="mt-5 mb-4">

    <h5 id="title_show mt-5" class="mb-3"><strong>Owner's information</strong></h5>

    <div class="owner-info">
      <p><strong>First Name: </strong><%= @pedalo.owner.first_name %></p>
      <p><strong>Last Name: </strong><%= @pedalo.owner.last_name %></p>
      <p><strong>Email Adress: </strong><%= @pedalo.owner.email%></p>
    </div>

    <hr class="mt-5 mb-4">

    <h5 id="title_show" class="mb-3"><strong>Review</strong></h5>
    <div class="d-flex flex-row flex-wrap">
    <% @pedalo.reviews.each do |review| %>
      <%= render 'reviews/card_review', review: review %>
    <% end %>
    </div>

    <hr class="mt-5 mb-4" >




  </div>
  <a class='btn-submit mt-2' href="<%= new_reservation_path(@pedalo.id) %>" >Book that pedalo!</a>

</div>

app/views/reservations/_card_reservation.html.erb
<div class="d-flex m-3 flex-row border justify-content-between align-items-center card-reservation">
  <%= image_tag(reservation.pedalo.image_link) %>
  <div class="ml-3 p-1">
    <h3 class="text-nowrap"><%= reservation.pedalo.name %></h3>
    <h4 class="text-nowrap"><%= reservation.pedalo.location %></h4>
    <div class="d-flex flex-row .justify-content-start align-items-center">
      <p class="text-nowrap"><strong>FROM</strong>: <%= reservation.start_time.strftime("%k:%M") %></p>
      <p class="text-nowrap ml-2"><strong>TO</strong>: <%= reservation.end_time.strftime("%k:%M") %></p>
      <% duration = (reservation.end_time - reservation.start_time) %>
      <% minute = ((duration%3600)/60).to_i %>
      <% hour = (duration/3600).to_i %>
      <p class="text-nowrap ml-2"><strong>DURATION</strong>: <%= "#{hour}h" unless hour.zero? %><%= " " if minute != 0 && hour != 0 %><%= "#{minute}mn" unless minute.zero? %></p>
    </div>
    <div class="d-flex flex-row .justify-content-start align-items-center">
      <p class="text-nowrap"><strong>DATE</strong>: <%= reservation.start_time.strftime("%-d %B %Y") %></p>
      <p class="text-nowrap ml-2"><strong>PRICE</strong>: <%= "#{reservation.transaction_price.fdiv(100).round(2)}" %> CHF</p>
    </div>
  </div>
  <div class="mr-4">
  <% if reservation.accepted == "pending" %>
    <i class="far fa-clock text-primary"></i>
  <% elsif reservation.accepted == "accepted" %>
    <i class="fas fa-check text-success"></i>
  <% else %>
    <i class="fas fa-times text-danger"></i>
  <% end %>
  </div>
</div>

app/views/reservations/index_res_pedalos.html.erb
<div class="container">
  <% @sorted_reservations.each do |reservation| %>
    <%= render 'reservations/card_reservation', reservation: reservation %>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class='container-sign-forms' style="width: 650px;">

  <h2 class='header-signup'>Book <span><%= @pedalo.name %></span> for: <strong><%= @date %></strong></h2>

  <%= simple_form_for [@pedalo, @reservation] do |f| %>
    <div class="form-inputs">
    <%= f.input :start_time, :label => "Start-time" %>
    <%= f.input :end_time, :label => "End-time" %>
    <%= f.submit "Book it!", class: 'btn-submit p-2 px-3' %>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<% if @reservation.accepted == "accepted" && @reservation.user_id != current_user.id%>
  <div class='container-sign-forms' style="width: 800px">
        <h2><strong>Booking Details: </strong></h2>
        <h3><span style="#2d4b8b">Pedalo Rented: </span><strong><%= @pedalo.name%></strong></h3>
        <h3><span style="#2d4b8b">Customer Name: </span><strong><%= @reservation.user.first_name%> <%= @reservation.user.last_name %> (<%= @reservation.user.age%> years old)</strong></h3>
        <h3><span style="#2d4b8b">Customer Email: </span><strong><%= @reservation.user.email%></strong></h3>
        <h3><span style="#2d4b8b">Start Time: </span><strong><%=  @reservation.start_time.strftime("%H:%M (%B %d, %Y)")%></strong></h3>
        <h3><span style="#2d4b8b">End Time: </span><strong><%= @reservation.end_time.strftime("%H:%M (%B %d, %Y)") %></strong></h3>
        <h3><span style="#2d4b8b">Total Price: </span><strong><%= @reservation.transaction_price.fdiv(100).round(2) %> CHF</strong></h3>
  </div>
<% elsif @reservation.accepted == "accepted" && @reservation.user_id == current_user.id%>
  <div class='container-sign-forms' style="width: 800px">
        <h2><strong>Booking Details: </strong></h2>
        <h3><span style="#2d4b8b">Pedalo Rented: </span><strong><%= @pedalo.name%></strong></h3>
        <h3><span style="#2d4b8b">Owner Name: </span><strong><%= @reservation.pedalo.owner.first_name%> <%= @reservation.pedalo.owner.last_name %> (<%= @reservation.user.age%> years old)</strong></h3>
        <h3><span style="#2d4b8b">Owner Email: </span><strong><%= @reservation.pedalo.owner.email%></strong></h3>
        <h3><span style="#2d4b8b">Start Time: </span><strong><%=  @reservation.start_time.strftime("%H:%M (%B %d, %Y)")%></strong></h3>
        <h3><span style="#2d4b8b">End Time: </span><strong><%= @reservation.end_time.strftime("%H:%M (%B %d, %Y)") %></strong></h3>
        <h3><span style="#2d4b8b">Request Status: </span><strong><%= @reservation.accepted.capitalize()%></strong></h3>
        <h3><span style="#2d4b8b">Total Price: </span><strong><%= @reservation.transaction_price.fdiv(100).round(2) %> CHF</strong></h3>
  </div>
<% elsif @reservation.user_id == current_user.id%>

    <div class='container-sign-forms' style="width: 800px">
      <h2>Thanks for booking <span style="#2d4b8b"><%= @pedalo.name%></span> !</h2>
      <h2>Your booking details:</h2>
      <h3><span style="#2d4b8b">Owner Name: </span><strong><%= @reservation.pedalo.owner.first_name%> <%= @reservation.pedalo.owner.last_name %> (<%= @reservation.user.age%> years old)</strong></h3>
      <h3><span style="#2d4b8b">Owner Email: </span><strong><%= @reservation.pedalo.owner.email%></strong></h3>
      <h3><span style="#2d4b8b">Start Time: </span><strong><%=  @reservation.start_time.strftime("%H:%M (%B %d, %Y)")%></strong></h3>
      <h3><span style="#2d4b8b">End Time: </span><strong><%= @reservation.end_time.strftime("%H:%M (%B %d, %Y)") %></strong></h3>
      <h3><span style="#2d4b8b">Request Status: </span><strong><%= @reservation.accepted.capitalize()%></strong></h3>
      <h3><span style="#2d4b8b">Total Price: </span><strong><%= @reservation.transaction_price.fdiv(100).round(2) %> CHF</strong></h3>

    </div>
<% elsif %>


<div class='container-sign-forms' style="width: 800px">
      <h2><span><%= @reservation.user.first_name %> <%= @reservation.user.last_name %> </span>requests to rent your pedalo <span style="#2d4b8b"><%= @pedalo.name %></span>!</h2>
      <h2>See booking details:</h2>
      <h3><span style="color: #2d4b8b">Customer Name: </span><strong><%= @reservation.user.first_name%> <%= @reservation.user.last_name %> (<%= @reservation.user.age%> years old)</strong></h3>
      <h3><span style="color: #2d4b8b">Customer Email: </span><strong><%= @reservation.user.email%></strong></h3>
      <h3><span style="color: #2d4b8b">Start Time: </span><strong><%=  @reservation.start_time.strftime("%H:%M (%B %d, %Y)")%></strong></h3>
      <h3><span style="color: #2d4b8b">End Time: </span><strong><%= @reservation.end_time.strftime("%H:%M (%B %d, %Y)") %></strong></h3>
      <h3><span style="color: #2d4b8b">Total Price: </span><strong><%= @reservation.transaction_price.fdiv(100).round(2) %> CHF</strong></h3>
      <%= simple_form_for [@pedalo, @reservation], url: reservation_path(@reservation.id), method: :patch do |f| %>
      <div class="form-inputs mt-5">
      <%= f.input :accepted, :label => "Do you want to accept this request ?", :collection => ['accepted', 'pending', 'declined'] %>
      <%= f.submit "Confirm", class: 'btn-submit p-2 px-3' %>
      </div>
      <% end %>
  </div>
<% end %>

app/views/reviews/_card_review.html.erb
<div class="d-flex p-3 m-3 flex-column align-items-start card-review">
  <div class="d-flex flex-row align-items-center">
    <img src="https://geeko.lesoir.be/wp-content/uploads/sites/58/2020/05/avatar.jpg" class="avatar ml-0 mb-3 mt-3 mr-3">
    <div class="d-flex flex-column justify-content-between">
      <h3 class="text-nowrap"><%= review.reservation.user.first_name %> <%= review.reservation.user.last_name.first %>.</h4>
      <p><%= review.reservation.start_time.strftime("%-d %b %Y") %><p>
    </div>
    <div class="m-3">
    <%= render 'reviews/rating', rating: review.rating %>
    </div>
  </div>
  <div>
    <p class="text-justify"><%= review.content %></p>
  </div>
</div>

app/views/users/_sidebar_user.html.erb
<div class="sidebar_user d-flex flex-column justify-content-start align-items-start p-3">
  <div class="w-100 d-flex justify-content-center mb-3">
    <img class="avatar-sidebar" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/JenniferAnistonFeb09.jpg/220px-JenniferAnistonFeb09.jpg">
  </div>
  <br>
  <p><strong>First Name - </strong><%= current_user.first_name %></p>
  <p><strong>Last Name - </strong> <%= current_user.last_name %></p>
  <p><strong>Age - </strong><%= current_user.age %></p>
  <p><strong>Email - </strong> <%= current_user.email %></p>
  <br>
  <br>
  <% unless current_user.role == "client" %>
    <div class="w-100 d-flex align-items-center flex-column">

      <%= link_to 'See your Pedalos', user_pedalos_path , id: "btn-sidebar" %>
      <%= link_to 'Add a Pedalo', new_pedalo_path, id: "btn-sidebar" %>
      <%= link_to 'See your Reservations', user_path , id: "btn-sidebar" %>

    </div>
  <% end %>
</div>

app/views/users/homepage_pedalo.html.erb
<div class="w-100 m-0 p-0">
  <div class="d-flex">
  <div class="sidenav">
    <%= render "users/sidebar_user" %>
  </div>
    <div class="d-flex flex-column align-items-center justify-content-start p-5 w-100">
      <% if ["owner", "admin"].include? current_user.role then %>

        <h2 class="text-light">Your Pedalos</h2>
        <div class="d-flex flex-row justify-content-start w-100 flex-wrap">
        <% if @pedalos.count.zero? %>
          <p class="text-light">You have no Pedalo</p>
          <<%= link_to "Add a Pedalo", new_pedalo_path, class: "btn-submit m-3" %>
        <% else %>
          <% @pedalos.each do |pedalo| %>
            <a href="<%= pedalo_path(pedalo) %>" class="text-reset">
              <%= render 'pedalos/card_pedalo', pedalo: pedalo %>
            </a>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>